### ISSUE TITLE
Got everything working except the tags field being missing making creation of servers impossible, great project btw

### ISSUE THREAD

**Issue by smashyalts** [tomo54321/McServer-List#3]
Can you also add the proxy repo back to github?
https://imgur.com/a/nCmmuaY (my issue)

**Comment by tomo54321** [comment]
Hey!

If you run `php artisan seed --class=ServerTagSeeder` this will load all the tags into the database for you. The idea was that an admin would setup predefined tags instead of allowing server owners to set their own.

I had potentially planned to revive the project but now wont so I have set the proxy back to [being public here ](https://github.com/tomo54321/mcserver-list-proxy) Just note that this is massively unfinished but you should be able to get an idea on how it was supposed to work with the site :)

**Comment by smashyalts** [comment]
https://imgur.com/a/FnYJ7oZ
that unfortunately didn't work

**Comment by smashyalts** [comment]
> Hey!
> 
> If you run `php artisan seed --class=ServerTagSeeder` this will load all the tags into the database for you. The idea was that an admin would setup predefined tags instead of allowing server owners to set their own.
> 
> I had potentially planned to revive the project but now wont so I have set the proxy back to [being public here ](https://github.com/tomo54321/mcserver-list-proxy) Just note that this is massively unfinished but you should be able to get an idea on how it was supposed to work with the site :)


https://imgur.com/a/FnYJ7oZ
that unfortunately didn't work

**Comment by tomo54321** [comment]
Looks like the seeder I updated the project and moved the models to App\Models instead. I've just done a quick commit for you so if you retry pulling the project and running the command it should work :)

**Comment by smashyalts** [comment]
Thank you! that and using db:seed instead of just seed worked like a charm
